name: CISA Vulnerability Check

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  cisa-vulnerability-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests PyGithub beautifulsoup4

      - name: Run CISA Bot
        env:
          CISA_TOKEN: ${{ secrets.CISA_TOKEN }}
        run: |
          python cisa_bot.py
