name: CISA Vulnerability Check

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  cisa-vulnerability-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      # Debug Token
      - name: Debug Token
        run: |
          echo "Token is set."

      # Validate Repository Context
      - name: Current Repository Context
        run: echo "Current Repository: $GITHUB_REPOSITORY"

      # Validate Token with API
      - name: Validate Token with API
        env:
          GITHUB_TOKEN: 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
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/ums91/CISA_BOT

      # Run CISA Bot
      - name: Run CISA Bot
        env:
          GITHUB_TOKEN: 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
        run: |
          python cisa_bot.py
